PUT http://localhost:3000/api/tasks/67e229f9bd26a1df1616a91c
Content-Type: application/json

{
    "title": "Updated Note Title",
    "description": "Updated content of the note.",
    "completed": true
}